server:
  port: 8189
jwt:
  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
  lifetime: 30m

spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/cw
    username: postgres
    password: admin
  main:
      allow-circular-references: true